name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8 ]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        run: ./mvnw package  -DskipTests=true
      - name: Upload JAR file
        uses: actions/upload-artifact@v2
        with:
          path: dubbo-admin-distribution/target/*.jar      
